### PR TITLE
Feature/modal style enhancements

### PR DESCRIPTION
**Pull request by colorful-tones**
This converts modal integration to use WP's Thickbox. #10

### CODE REVIEW

**Comment by brashrebel** [comment]
This looks really amazing! I'll review it in greater detail later this week and most likely merge then. Thanks @colorful-tones!

**Comment by colorful-tones** [comment]
👍  if needs adjusting just holler. Also, if/when merged then I'm happy to work on/continue modal styling as well. Cheers.

**Comment by colorful-tones** [comment]
Shoot, just realized #hacktoberfest doesn't officially start until Oct. 1. So take your time merging, but happy to help either way. :-D

**Comment by brashrebel** [comment]
Oh great point! Yeah, not a problem. I'll review and get this merged early next week. Excellent work!

**Pull request closed without merging**
